@Observability_WebApi_Blazor.Backend_HostAddress = http://localhost:5107

GET {{Observability_WebApi_Blazor.Backend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Observability_WebApi_Blazor.Backend_HostAddress}}/api/chat/send
Content-Type: application/json

{
  "user": "user1",
  "message": "hello from http"
}

###
